apiVersion: skaffold/v4beta10
kind: Config
metadata:
  name: ticketing-app
build:
  local:
    push: true
  artifacts:
    - image: kodega2016/ticketing_auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
    - image: kodega2016/ticketing_client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "**/*.js"
manifests:
  rawYaml:
    - infra/k8s/*
