apiVersion: skaffold/v4beta10
kind: Config
metadata:
  name: ticketing-app
build:
  local:
    push: false
  artifacts:
    - image: kodega2016/ticketing_auth
      context: auth
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - infra/k8s/*
