apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-deployment
  labels:
    app: expiration
spec:
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
        - name: expiration
          image: kodega2016/ticketing_expiration
          imagePullPolicy: IfNotPresent
          env:
            - name: NATS_URL
              value: http://nats-clusterip-service:4222
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
