apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-deployment
  labels:
    app: tickets
spec:
  selector:
    matchLabels:
      app: tickets
  replicas: 1
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        - name: tickets
          image: kodega2016/ticketing_tickets
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: tickets
          env:
            - name: MONGO_DB_URI
              value: tickets-mongo-clusterip-service
            - name: NATS_URL
              value: http://nats-clusterip-service:4222
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-clusterip-service
  namespace: default
spec:
  selector:
    app: tickets
  type: ClusterIP
  ports:
    - name: ticketing-clusterip-service
      protocol: TCP
      port: 3000
      targetPort: 3000
