name: testing-tickets
on:
  pull_request:
    paths:
      - "tickets/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v4
      - name: run test of tickets
        run: cd tickets && npm install && npm run test:ci
